name: model_example
description: Complete model demonstration project
homepage: https://github.com/squarealfa/dart_framework/tree/main/proto_mapper/proto_mapper_example
repository: https://github.com/squarealfa/dart_framework
version: 1.0.0

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  proto_annotations: ^1.0.0
  map_mapper_annotations: ^1.0.0

dev_dependencies:
  build_runner: ^1.12.2
  pedantic: ^1.9.0
  map_mapper_generator: ^1.0.1
  proto_generator: ^1.0.0
  test: ^1.14.4
