name: defaults_provider_generator
description: Generates business class Defaults Providers, that provide default values for non-nullable PODO properties
homepage: https://github.com/squarealfa/dart_framework/tree/main/defaults_provider/defaults_provider_generator
repository: https://github.com/squarealfa/dart_framework
version: 1.1.2

environment:
  sdk: '>=2.12.0 <3.0.0'

publish_to: none

dependencies:
  source_gen: ^1.0.0
  decimal: ^1.0.0
  defaults_provider_annotations: #^1.1.0
    path: ../defaults_provider_annotations
  squarealfa_generators_common: #^1.0.0
    path: /home/ruicraveiro/sources/dart_framework/generators_common
  analyzer: ^1.3.0
  build: ^2.0.0


dev_dependencies:
  pedantic: ^1.9.0

