name: example
description: Example for squarealfa_validation_generator
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  squarealfa_entity_adapter:
    path: ../entity_adapter
  decimal: ^1.0.0
  fixnum: ^1.0.0

dev_dependencies:
  squarealfa_entity_adapter_generator:
    path: ../entity_adapter_generator

  build_runner: ^1.10.2
  build_verify: ^2.0.0
  pedantic: ^1.11.0
  test: ^1.16.8
