name: arangodb_repository
description: Concrete implementation of the nosql_repository package for the ArangoDB database.
repository: https://github.com/squarealfa/dart_framework
homepage: https://github.com/squarealfa/dart_framework/tree/main/arango_repository
version: 1.0.3

environment:
  sdk: '>=2.12.0 <3.0.0'

publish_to: none

dependencies:
  arango_driver: #^1.0.2
    path: ../arango_driver
  nosql_repository: #^1.0.2
    path: ../nosql_repository
  squarealfa_security: #^1.0.3
    path: ../squarealfa_security
  tuple: ^2.0.0

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.8
  nosql_repository_tests:
    path: ../nosql_repository_tests

