name: arango_driver
description: ArangoDB driver, working on top of ArangoDB HTTP API. This package is a fork of the dart_arango_min package.
repository: https://github.com/squarealfa/dart_framework
homepage: https://github.com/squarealfa/dart_framework/tree/main/arango_driver
version: 1.1.2

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.11
