name: squarealfa_entity_generator
description: 
  Code generators that augment classes that are meant to be used as business entities
homepage: https://github.com/squarealfa/dart_framework/tree/entity/entity/entity_generator
repository: https://github.com/squarealfa/dart_framework
version: 1.1.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^1.2.0
  build: ^2.0.0
  decimal: ^1.0.0
  source_gen: ^1.0.0
  squarealfa_entity_annotations: ^1.1.0
  squarealfa_generators_common: ^1.0.0
  tuple: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.0
