name: squarealfa_entity_adapter_generator
description: Generates a facade to several SquareAlfa framework services that are required to expose PODOs via gRPC services.
homepage: https://github.com/squarealfa/dart_framework/tree/main/entity_adapter/entity_adapter_generator
repository: https://github.com/squarealfa/dart_framework/

version: 1.0.0


environment:
  sdk: '>=2.12.0 <3.0.0'

publish_to: none

dependencies:
  source_gen: ^1.0.0
  squarealfa_entity_adapter: #^1.0.0
    path: ../entity_adapter
  map_mapper_generator: #^1.2.0
    path: /home/ruicraveiro/sources/dart_framework/map_mapper/map_mapper_generator
  proto_generator: #^1.2.0
    path: /home/ruicraveiro/sources/dart_framework/proto_mapper/proto_generator
  defaults_provider_generator: #^1.1.0
    path: /home/ruicraveiro/sources/dart_framework/defaults_provider/defaults_provider_generator
  squarealfa_entity_generator: #^1.1.0
    path: /home/ruicraveiro/sources/dart_framework/entity/entity_generator
  analyzer: ^1.2.0
  build: ^2.0.0


dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
