name: squarealfa_generators_common
description: This package provides a set of helpers and extensions to facilitate the reflection over classes that serving as the basis for code generation.
homepage: https://github.com/squarealfa/dart_framework/tree/main/generators_common
repository: https://github.com/squarealfa/dart_framework
version: 1.0.1


environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  source_gen: ^1.0.0
  analyzer: ^1.3.0
  build: ^2.0.0
  build_resolvers: ^2.0.0
  build_test: ^2.0.0
  
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
