name: proto_annotations
description: Annotations to mark and configure business model classes for code generation of .proto and Dart mapper classes
homepage: https://github.com/squarealfa/dart_framework/tree/main/proto_mapper/proto_annotations
repository: https://github.com/squarealfa/dart_framework
version: 1.1.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  fixnum: ^1.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
