name: mongo_security_repository
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  nosql_repository:
    path: /home/ruicraveiro/sources/dart_framework/nosql_repository
  security_repository:
    path: ../security_repository
  mongo_repository:
    path: ../mongo_repository
  mongo_dart: ^0.7.0+1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
