name: map_mapper_example
description: map_mapper_annotations and map_mapper_generator packages demonstration project
homepage: https://github.com/squarealfa/dart_framework/tree/main/map_mapper/map_mapper_example
repository: https://github.com/squarealfa/dart_framework
version: 1.0.0

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  map_mapper_annotations: 
    path: ../map_mapper_annotations

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

  map_mapper_generator: 
    path: ../map_mapper_generator
  build_runner: ^1.12.2
